spring.application.name=order-management-system
server.port=${PORT:8080}


# temporary 
spring.datasource.url=jdbc:mysql://localhost:3306/oms_db
spring.datasource.username=root
spring.datasource.password=Mukesh77@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# temporary