name: Dev to Main Pipeline

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ===== Backend =====
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend
        working-directory: backend/OMS_backend
        run: mvn clean install -DskipTests

      # ===== Frontend =====
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: frontend/OMS_frontend_angular
        run: npm install

      - name: Skip Angular Tests
        run: echo "Skipping frontend tests"

      - name: Build Angular
        working-directory: frontend/OMS_frontend_angular
        run: npm run build -- --configuration production

      # ===== Merge dev → main =====
      - name: Merge dev into main
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git fetch origin
          git checkout main
          git merge origin/dev --allow-unrelated-histories --no-ff -m "Auto merge dev to main"
          git push origin main